apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-limits
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: banking
    server: {{ .Values.spec.destination.server }}
  project: banking    
  source:
    helm:
      version: v3
      valueFiles:
      - values-sit.yaml
    path: ./
    repoURL: https://github.com/paas2-bnk/limits.api.helm
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true     
    automated:  
      prune: true         